# syntax=docker/dockerfile:1

# Create a stage for building the application.
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build
# Copy .sln file
COPY *.sln /p/source/
# Copy everything else
COPY . /p/source/
WORKDIR /p/source
# Restore
RUN dotnet restore
RUN dotnet build -c Debug
#RUN dotnet test -c Release
#WORKDIR /source/Web/ProxyService.Web


# This is the architecture you’re building for, which is passed in by the builder.
# Placing it here allows the previous steps to be cached across architectures.
#ARG TARGETARCH

# Build the application.
# Leverage a cache mount to /root/.nuget/packages so that subsequent builds don't have to re-download packages.
# If TARGETARCH is "amd64", replace it with "x64" - "x64" is .NET's canonical name for this and "amd64" doesn't
#   work in .NET 6.0.
#RUN --mount=type=cache,id=nuget,target=/root/.nuget/packages \
#    dotnet publish -a ${TARGETARCH/amd64/x64} --use-current-runtime --self-contained false -o /app
#WORKDIR /source
# test-build builds the xUnit test project
#FROM build AS test-build
#WORKDIR /source
#COPY --link tests/*.csproj tests/
#WORKDIR /source/tests
#RUN dotnet restore

#COPY --link tests/ .
#RUN dotnet build --no-restore

# test-entrypoint exposes tests as the default executable for the stage
FROM build AS test
WORKDIR /p
RUN ls
COPY --from=build /bin /bin/
RUN ls bin/net8.0/*
RUN ls bin/net8.0/*Tests.dll
RUN dotnet test bin/net8.0/*Tests.dll
ENTRYPOINT ["dotnet", "test", "bin/net8.0/*Tests.dll", "--no-build", "--logger:trx"]

# If you need to enable globalization and time zones:
# https://github.com/dotnet/dotnet-docker/blob/main/samples/enable-globalization.md
################################################################################
# Create a new stage for running the application that contains the minimal
# runtime dependencies for the application. This often uses a different base
# image from the build stage where the necessary files are copied from the build
# stage.
#
# The example below uses an aspnet alpine image as the foundation for running the app.
# It will also use whatever happens to be the most recent version of that tag when you
# build your Dockerfile. If reproducibility is important, consider using a more specific
# version (e.g., aspnet:7.0.10-alpine-3.18),
# or SHA (e.g., mcr.microsoft.com/dotnet/aspnet@sha256:f3d99f54d504a21d38e4cc2f13ff47d67235efeeb85c109d3d1ff1808b38d034).
FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine AS final
ENV ASPNETCORE_ENVIRONMENT=Development
WORKDIR /app
ENV ASPNETCORE_URLS=http://*:8080
EXPOSE 8080

# Copy everything needed to run the app from the "build" stage.
COPY --from=build /app .

# Switch to a non-privileged user (defined in the base image) that the app will run under.
# See https://docs.docker.com/go/dockerfile-user-best-practices/
# and https://github.com/dotnet/dotnet-docker/discussions/4764
USER $APP_UID

ENTRYPOINT ["dotnet", "ProxyService.Web.dll"]
